---
title: "Breast Cancerdata"
author: "chaitu"
date: "October 15, 2017"
output: html_document
---


```{r, message=FALSE, warning=FALSE, include=FALSE}
library(readr)
BreastCancerData <- read_csv("C:/Users/chaitanya/Desktop/Data science/data.csv")


```


```{r}
bcd = BreastCancerData #Saving the data into another space to work on it freely
attach(bcd) # Attaching the dataset for easier usage
str(bcd) # Checking the structure of the dataset

bcd = bcd[-33] # Removing the last variable which is the dirty variable
bcd = bcd[-1] #Removing the first variable as it is the ID and is not really important as ID is not used in the Data Analysis

# Encoding the target feature as factor
bcd$diagnosis = factor(bcd$diagnosis)
#bcd$diagnosis = factor(bcd$diagnosis, labels = c(0,1))  # In case you need them to be in binary format


```

```{r}
# Splitting the dataset into the Training set and Test set
# install.packages('caTools')
library(caTools)
set.seed(123)
split = sample.split(bcd$diagnosis, SplitRatio = 0.75)
training_set = subset(bcd, split == TRUE)
test_set = subset(bcd, split == FALSE)
```

```{r}
# Fitting Logistic Regression to the Training set
classifier = glm(formula = diagnosis ~ .,
                 family = "binomial",
                 data = training_set)
summary(classifier)
```
```{r}
# Predicting the Test set results
prob_pred = predict(classifier, type = 'response', newdata = test_set)

# Getting the cutoff for the predictions
# install.packages("InformationValue")
# install.packages("scales")
library(InformationValue)
optcutoff <- optimalCutoff(test_set$diagnosis,prob_pred)
optcutoff

y_pred = ifelse(prob_pred > optcutoff, 1, 0)

```




